import type { HelpFlowStep } from '../types';

export const usageFlowSteps: HelpFlowStep[] = [
  {
    id: 'criar-conta',
    title: '1. Criar sua conta',
    objective: 'Ter acesso ao Valora com e-mail e senha.',
    explanation:
      'Na tela Criar conta, informe nome, e-mail e senha. Em alguns casos pode ser necessário confirmar o e-mail antes de entrar.',
    example: 'Cadastro com nome “Ana”, e-mail e senha seguros.',
    expectedResult: 'Conta criada e, com sessão ativa, redirecionamento ao Dashboard.',
    href: '/register',
  },
  {
    id: 'acessar',
    title: '2. Acessar o sistema',
    objective: 'Entrar na área autenticada.',
    explanation: 'Use Entrar com o mesmo e-mail e senha. Se esquecer a senha, use Recuperar senha.',
    example: 'Login bem-sucedido leva à Visão geral.',
    expectedResult: 'Sidebar com Dashboard, Carteiras, Categorias, Transações e demais menus.',
    href: '/login',
  },
  {
    id: 'carteira',
    title: '3. Criar uma carteira',
    objective: 'Definir onde o dinheiro vive no sistema.',
    explanation: 'Sem carteira não há como lançar transações. Comece por uma conta principal.',
    example: '“Conta corrente” com saldo inicial R$ 1.000,00.',
    expectedResult: 'Carteira listada e pronta para uso.',
    href: '/carteiras',
  },
  {
    id: 'categorias',
    title: '4. Criar categorias',
    objective: 'Classificar receitas e despesas.',
    explanation: 'Crie ao menos uma categoria de receita e uma de despesa.',
    example: 'Salário (Receita) e Alimentação (Despesa).',
    expectedResult: 'Categorias disponíveis no formulário de transações.',
    href: '/categorias',
  },
  {
    id: 'transacoes',
    title: '5. Cadastrar receitas e despesas',
    objective: 'Registrar a realidade financeira.',
    explanation:
      'Em Transações, escolha a categoria (o tipo receita ou despesa vem dela) e preencha valor, carteira e data.',
    example: 'Salário R$ 3.000 e supermercado R$ 150 em Alimentação.',
    expectedResult: 'Histórico preenchido e saldos atualizados.',
    href: '/transacoes',
  },
  {
    id: 'dashboard',
    title: '6. Acompanhar o Dashboard',
    objective: 'Ver o resumo do período.',
    explanation:
      'Ajuste o intervalo de datas e leia saldo, receitas, despesas, resultado e gastos por categoria.',
    example: 'No mês: saldo R$ 2.500, receitas R$ 3.000, despesas R$ 1.500, resultado R$ 4.000.',
    expectedResult: 'Visão clara da saúde financeira no período.',
    href: '/dashboard',
  },
  {
    id: 'orcamento',
    title: '7. Definir um orçamento',
    objective: 'Limitar gastos mensais por categoria.',
    explanation: 'Crie o orçamento do mês e defina tetos nas categorias de despesa.',
    example: 'Alimentação com limite de R$ 800,00.',
    expectedResult: 'Status Dentro ou Acima conforme as despesas lançadas.',
    href: '/orcamentos',
  },
  {
    id: 'metas',
    title: '8. Criar metas financeiras',
    objective: 'Trabalhar rumo a um objetivo.',
    explanation: 'Defina o valor-alvo e registre o progresso periodicamente.',
    example: 'Meta “Reserva” de R$ 10.000 com 20% concluídos.',
    expectedResult: 'Barra de progresso atualizada.',
    href: '/metas',
  },
  {
    id: 'investimentos',
    title: '9. Registrar investimentos',
    objective: 'Acompanhar ativos e movimentos.',
    explanation: 'Cadastre o ativo e lance compras, vendas ou dividendos.',
    example: 'Fundo XYZ com compra inicial.',
    expectedResult: 'Posição com quantidade e preço médio.',
    href: '/investments',
  },
  {
    id: 'mercado',
    title: '10. Explorar o Mercado',
    objective: 'Consultar cotações, taxas e notícias.',
    explanation: 'Use a área Mercado para contexto externo — sem alterar seus lançamentos.',
    example: 'Ver câmbio do dólar e notícias do dia.',
    expectedResult: 'Informação de mercado atualizada para consulta.',
    href: '/',
  },
];
